#!/bin/sh
#  _____             _ _ _ ____  _____ _____ 
# |     |___ ___ ___| | | |    \|_   _|  |  |
# |  |  | . | -_|   | | | |  |  | | | |  |  |
# |_____|  _|___|_|_|_____|____/  |_|  \___/ 
#       |_| http://openwdtv.org

#####################
# SETUP ENVIRONMENT #
#####################
. ./sysconfig
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
/bin/mount -t proc none /proc
echo "1 1 1 7" > /proc/sys/kernel/printk
mount -t sysfs sysfs /sys
mount -t usbfs usb /proc/bus/usb
echo /sbin/mdev > /proc/sys/kernel/hotplug
mount -t tmpfs mdev /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts
mdev -s
mount -t tmpfs none /tmp
/bin/hostname -F /etc/hostname

########################
# CREATE INPUT DEVICES #
########################
mkdir -p /dev/input
MINOR=0
while [ $MINOR -lt 17 ]; do
    mknod /dev/input/event$MINOR c 13 `expr $MINOR + 64`;
    MINOR=`expr $MINOR + 1`;
done

####################################
# CREATE SYMLINKS TO BLOCK DEVICES #
####################################
ln -s $SYSCONF_BOOTLOADER_MTD_PARTITION /dev/mtdblock_bootloader
ln -s $SYSCONF_KERNEL_MTD_PARTITION /dev/mtdblock_kernel
ln -s $SYSCONF_FIRMWARE_MTD_PARTITION /dev/mtdblock_romfs

############################
# SETUP TTY LOGIN SECURITY #
############################
[ ! -f /conf/securetty.ori ] && cp /etc/securetty.ori /conf/
ln -s /conf/securetty.ori /tmp/securetty.ori

##############################
# SETUP SHARED LIBRARY LINKS #
##############################
/sbin/ldconfig -C /tmp/ld.so.cache

######################
# LOAD CONFIGURATION #
######################
if [ $1 == "upgrade" ]; then
    # Only load, don't monitor
    /sbin/config_tool -l 
    # Free up some memory
    touch /tmp/STOP_DMARENDER
    touch /tmp/STOP_PICRENDER
else
    # Load config and continue to monitor for changes
    /sbin/config_tool -l -m 10 &
fi

#################################
# MOUNT STATIC CONFIG PARTITION #
#################################
if [ x$1 != "xf1f1" ]; then
    if [ x$SYSCONF_LAST_PARTITION_NODE_NAME != "x" ]; then
        dd if=$SYSCONF_LAST_PARTITION_NODE_NAME of=/tmp/lastblock bs=1024
        mkdir $SYSCONF_STATIC_CONFIG_MOUNT_POINT
        mount -t minix -o loop /tmp/lastblock $SYSCONF_STATIC_CONFIG_MOUNT_POINT
    fi
fi

##################
# EXPORT DISPLAY #
##################
export EM8XXX_SERVER=":0"

############################
# CREATE MISC DEVICE NODES #
############################
mknod /dev/mum0 c 126 0
mknod /dev/em8xxx0 c 127 0
mknod /dev/mtdblock3 b 254 6
mknod /dev/mtdblock2 b 254 3
mknod /dev/mtdblock0 b 254 0
mknod /dev/sda1 b 8 1

###################
# RELOAD FIRMWARE #
###################
fw_reload_t3.sh

###########################
# LOAD REALTEK NIC DRIVER #
###########################
modprobe r8169

##################
# LOAD IR MODULE #
##################
MAJOR=254
while [ -f /lib/modules/irkernel.ko ]; do
    insmod /lib/modules/irkernel.ko major_num=$MAJOR;
    if [ $? == 0 ]; then
        mknod /dev/ir c $MAJOR 0
        break;
    fi
    MAJOR=`expr $MAJOR - 1`
    if [ $MAJOR == 1 ]; then
        break;
    fi
done
ln -s /dev/ir /dev/irda

####################################
# LOAD LED AND RESET BUTTON DRIVER #
####################################
MAJOR=254
while [ -f /lib/modules/wd_led_rst.ko ]; do
    insmod /lib/modules/wd_led_rst.ko major_num=$MAJOR;
    if [ $? == 0 ]; then
    mknod /dev/led_rst c $MAJOR 0
        break;
    fi
    MAJOR=`expr $MAJOR - 1`
    if [ $MAJOR == 1 ]; then
        break;
    fi
done

######################################
# LOAD PROCESS STDOUT STDIN PIPELINE #
######################################
[ -f /lib/modules/proc_pipe.ko ] && insmod /lib/modules/proc_pipe.ko

#####################
# POPULATE IR TABLE #
#####################
[ -f /ir_table ] && cat /ir_table > /proc/tangoxfreq/ir_table

##############################
# MISC KERNEL MODULE LOADING #
##############################
# Paragon NTFS driver
[ -f /lib/modules/ufsd.ko ] && insmod /lib/modules/ufsd.ko
# Frequency scaling driver
[ -f /lib/modules/fctrl.ko ] && insmod /lib/modules/fctrl.ko
# llad kernel module for standalone configuration.... WHAT?
[ -f /lib/modules/llad.ko ] && insmod -f /lib/modules/llad.ko

####################
# LOAD CIFS MODULE #
####################
modprobe cifs CIFSMaxBufSize=64512

##########################
# SETUP USB MOUNT POINTS #
##########################
mkdir -p /tmp/media
mkdir -p /tmp/media/usb

##################################
# SETUP LOCAL LOOPBACK INTERFACE #
##################################
ifconfig lo 127.0.0.1

#################################################
# SYMLINK LOGIN CREDENTIALS TO CONFIG PARTITION #
#################################################
[ ! -f /conf/passwd.conf ] && cp /etc/passwd.conf /conf/
ln -s /conf/passwd.conf /tmp/passwd.conf
[ ! -f /conf/shadow.conf ] && cp /etc/shadow.conf /conf/
ln -s /conf/shadow.conf /tmp/shadow.conf

######################
# LOAD CACHE SERVICE #
######################
/bin/memory_cache_server &

########################
# SPAWN INIT.D SCRIPTS #
########################
/etc/init.d/rcS $1 $2 $3&

#################################
# START SUPER HAPPY FUN LOOP :) #
#################################
while [ 1 ]; do
    /bin/sh ;
done
