#!/bin/sh
#  _____             _ _ _ ____  _____ _____ 
# |     |___ ___ ___| | | |    \|_   _|  |  |
# |  |  | . | -_|   | | | |  |  | | | |  |  |
# |_____|  _|___|_|_|_____|____/  |_|  \___/ 
#       |_| http://openwdtv.org

case "$1" in
    start)
	httpd -h /www
        ;;
    stop)
        killall httpd
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)  
        echo "Usage: $0 (start|stop|restart)"
        ;;
esac

exit 0
