#!/bin/sh

case "$1" in
    start)
	httpd -h /www
        ;;
    stop)
        killall httpd
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)  
        echo "Usage: $0 (start|stop|restart)"
        ;;
esac

exit 0
