#!/bin/sh
#  _____             _ _ _ ____  _____ _____
# |     |___ ___ ___| | | |    \|_   _|  |  |
# |  |  | . | -_|   | | | |  |  | | | |  |  |
# |_____|  _|___|_|_|_____|____/  |_|  \___/
#       |_| http://openwdtv.org

if [ "`config read ENABLE_APPS`" == "1" ]; then

    logger -s -t $0 "Scanning external media for app.bin files..."
    INTAPPS=`find /apps/ -type f -name "*.app.bin"`
    EXTAPPS=`find /tmp/media/usb/ -type f -name "*.app.bin"`

    for i in $INTAPPS $EXTAPPS; do
        logger -s -t $0 "Mounting $i on root..."
        mount -o bind $i /
    done
fi